VERSION 0.8

build:
  FROM --platform=linux/amd64 oven/bun
  RUN apt update && apt install python3 build-essential -y
  WORKDIR /usr/src/app
  COPY package.json bun.lock .
  RUN bun install --frozen-lockfile
  COPY --dir src .
  ENTRYPOINT bun run src/main.ts
  SAVE IMAGE --push ghcr.io/shepherdjerred/homelab:latest

run:
  FROM +build
  COPY .env .
  RUN bun run src/main.ts
