// deno-lint-ignore-file

// generated by cdk8s
import {
  ApiObject,
  ApiObjectMetadata,
  GroupVersionKind,
} from "https://esm.sh/cdk8s@2.68.58";
import { Construct } from "https://esm.sh/constructs@10.3.0";

/**
 * @schema Connector
 */
export class Connector extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Connector"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: "tailscale.com/v1alpha1",
    kind: "Connector",
  };

  /**
   * Renders a Kubernetes manifest for "Connector".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ConnectorProps): any {
    return {
      ...Connector.GVK,
      ...toJson_ConnectorProps(props),
    };
  }

  /**
   * Defines a "Connector" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ConnectorProps) {
    super(scope, id, {
      ...Connector.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...Connector.GVK,
      ...toJson_ConnectorProps(resolved),
    };
  }
}

/**
 * @schema Connector
 */
export interface ConnectorProps {
  /**
   * @schema Connector#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * ConnectorSpec describes the desired Tailscale component.
   *
   * @schema Connector#spec
   */
  readonly spec: ConnectorSpec;
}

/**
 * Converts an object of type 'ConnectorProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ConnectorProps(
  obj: ConnectorProps | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "metadata": obj.metadata,
    "spec": toJson_ConnectorSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * ConnectorSpec describes the desired Tailscale component.
 *
 * @schema ConnectorSpec
 */
export interface ConnectorSpec {
  /**
   * ExitNode defines whether the Connector node should act as a Tailscale exit node. Defaults to false. https://tailscale.com/kb/1103/exit-nodes
   *
   * @default false. https://tailscale.com/kb/1103/exit-nodes
   * @schema ConnectorSpec#exitNode
   */
  readonly exitNode?: boolean;

  /**
   * Hostname is the tailnet hostname that should be assigned to the Connector node. If unset, hostname defaults to <connector name>-connector. Hostname can contain lower case letters, numbers and dashes, it must not start or end with a dash and must be between 2 and 63 characters long.
   *
   * @schema ConnectorSpec#hostname
   */
  readonly hostname?: string;

  /**
   * ProxyClass is the name of the ProxyClass custom resource that contains configuration options that should be applied to the resources created for this Connector. If unset, the operator will create resources with the default configuration.
   *
   * @schema ConnectorSpec#proxyClass
   */
  readonly proxyClass?: string;

  /**
   * SubnetRouter defines subnet routes that the Connector node should expose to tailnet. If unset, none are exposed. https://tailscale.com/kb/1019/subnets/
   *
   * @schema ConnectorSpec#subnetRouter
   */
  readonly subnetRouter?: ConnectorSpecSubnetRouter;

  /**
   * Tags that the Tailscale node will be tagged with. Defaults to [tag:k8s]. To autoapprove the subnet routes or exit node defined by a Connector, you can configure Tailscale ACLs to give these tags the necessary permissions. See https://tailscale.com/kb/1018/acls/#auto-approvers-for-routes-and-exit-nodes. If you specify custom tags here, you must also make the operator an owner of these tags. See  https://tailscale.com/kb/1236/kubernetes-operator/#setting-up-the-kubernetes-operator. Tags cannot be changed once a Connector node has been created. Tag values must be in form ^tag:[a-zA-Z][a-zA-Z0-9-]*$.
   *
   * @default tag:k8s]. To autoapprove the subnet routes or exit node defined by a Connector, you can configure Tailscale ACLs to give these tags the necessary permissions. See https://tailscale.com/kb/1018/acls/#auto-approvers-for-routes-and-exit-nodes. If you specify custom tags here, you must also make the operator an owner of these tags. See  https://tailscale.com/kb/1236/kubernetes-operator/#setting-up-the-kubernetes-operator. Tags cannot be changed once a Connector node has been created. Tag values must be in form ^tag:[a-zA-Z][a-zA-Z0-9-]*$.
   * @schema ConnectorSpec#tags
   */
  readonly tags?: string[];
}

/**
 * Converts an object of type 'ConnectorSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ConnectorSpec(
  obj: ConnectorSpec | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "exitNode": obj.exitNode,
    "hostname": obj.hostname,
    "proxyClass": obj.proxyClass,
    "subnetRouter": toJson_ConnectorSpecSubnetRouter(obj.subnetRouter),
    "tags": obj.tags?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * SubnetRouter defines subnet routes that the Connector node should expose to tailnet. If unset, none are exposed. https://tailscale.com/kb/1019/subnets/
 *
 * @schema ConnectorSpecSubnetRouter
 */
export interface ConnectorSpecSubnetRouter {
  /**
   * AdvertiseRoutes refer to CIDRs that the subnet router should make available. Route values must be strings that represent a valid IPv4 or IPv6 CIDR range. Values can be Tailscale 4via6 subnet routes. https://tailscale.com/kb/1201/4via6-subnets/
   *
   * @schema ConnectorSpecSubnetRouter#advertiseRoutes
   */
  readonly advertiseRoutes: string[];
}

/**
 * Converts an object of type 'ConnectorSpecSubnetRouter' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ConnectorSpecSubnetRouter(
  obj: ConnectorSpecSubnetRouter | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "advertiseRoutes": obj.advertiseRoutes?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ProxyClass
 */
export class ProxyClass extends ApiObject {
  /**
   * Returns the apiVersion and kind for "ProxyClass"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: "tailscale.com/v1alpha1",
    kind: "ProxyClass",
  };

  /**
   * Renders a Kubernetes manifest for "ProxyClass".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ProxyClassProps): any {
    return {
      ...ProxyClass.GVK,
      ...toJson_ProxyClassProps(props),
    };
  }

  /**
   * Defines a "ProxyClass" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ProxyClassProps) {
    super(scope, id, {
      ...ProxyClass.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...ProxyClass.GVK,
      ...toJson_ProxyClassProps(resolved),
    };
  }
}

/**
 * @schema ProxyClass
 */
export interface ProxyClassProps {
  /**
   * @schema ProxyClass#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema ProxyClass#spec
   */
  readonly spec: ProxyClassSpec;
}

/**
 * Converts an object of type 'ProxyClassProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassProps(
  obj: ProxyClassProps | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "metadata": obj.metadata,
    "spec": toJson_ProxyClassSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ProxyClassSpec
 */
export interface ProxyClassSpec {
  /**
   * Proxy's StatefulSet spec.
   *
   * @schema ProxyClassSpec#statefulSet
   */
  readonly statefulSet: ProxyClassSpecStatefulSet;
}

/**
 * Converts an object of type 'ProxyClassSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpec(
  obj: ProxyClassSpec | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "statefulSet": toJson_ProxyClassSpecStatefulSet(obj.statefulSet),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Proxy's StatefulSet spec.
 *
 * @schema ProxyClassSpecStatefulSet
 */
export interface ProxyClassSpecStatefulSet {
  /**
   * Annotations that will be added to the StatefulSet created for the proxy. Any Annotations specified here will be merged with the default annotations applied to the StatefulSet by the Tailscale Kubernetes operator as well as any other annotations that might have been applied by other actors. Annotations must be valid Kubernetes annotations. https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
   *
   * @schema ProxyClassSpecStatefulSet#annotations
   */
  readonly annotations?: { [key: string]: string };

  /**
   * Labels that will be added to the StatefulSet created for the proxy. Any labels specified here will be merged with the default labels applied to the StatefulSet by the Tailscale Kubernetes operator as well as any other labels that might have been applied by other actors. Label keys and values must be valid Kubernetes label keys and values. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
   *
   * @schema ProxyClassSpecStatefulSet#labels
   */
  readonly labels?: { [key: string]: string };

  /**
   * Configuration for the proxy Pod.
   *
   * @schema ProxyClassSpecStatefulSet#pod
   */
  readonly pod?: ProxyClassSpecStatefulSetPod;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSet' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSet(
  obj: ProxyClassSpecStatefulSet | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "annotations": ((obj.annotations) === undefined)
      ? undefined
      : (Object.entries(obj.annotations).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
    "labels": ((obj.labels) === undefined)
      ? undefined
      : (Object.entries(obj.labels).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
    "pod": toJson_ProxyClassSpecStatefulSetPod(obj.pod),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Configuration for the proxy Pod.
 *
 * @schema ProxyClassSpecStatefulSetPod
 */
export interface ProxyClassSpecStatefulSetPod {
  /**
   * Annotations that will be added to the proxy Pod. Any annotations specified here will be merged with the default annotations applied to the Pod by the Tailscale Kubernetes operator. Annotations must be valid Kubernetes annotations. https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
   *
   * @schema ProxyClassSpecStatefulSetPod#annotations
   */
  readonly annotations?: { [key: string]: string };

  /**
   * Proxy Pod's image pull Secrets. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
   *
   * @schema ProxyClassSpecStatefulSetPod#imagePullSecrets
   */
  readonly imagePullSecrets?: ProxyClassSpecStatefulSetPodImagePullSecrets[];

  /**
   * Labels that will be added to the proxy Pod. Any labels specified here will be merged with the default labels applied to the Pod by the Tailscale Kubernetes operator. Label keys and values must be valid Kubernetes label keys and values. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
   *
   * @schema ProxyClassSpecStatefulSetPod#labels
   */
  readonly labels?: { [key: string]: string };

  /**
   * Proxy Pod's node name. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling
   *
   * @schema ProxyClassSpecStatefulSetPod#nodeName
   */
  readonly nodeName?: string;

  /**
   * Proxy Pod's node selector. By default Tailscale Kubernetes operator does not apply any node selector. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling
   *
   * @schema ProxyClassSpecStatefulSetPod#nodeSelector
   */
  readonly nodeSelector?: { [key: string]: string };

  /**
   * Proxy Pod's security context. By default Tailscale Kubernetes operator does not apply any Pod security context. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-2
   *
   * @schema ProxyClassSpecStatefulSetPod#securityContext
   */
  readonly securityContext?: ProxyClassSpecStatefulSetPodSecurityContext;

  /**
   * Configuration for the proxy container running tailscale.
   *
   * @schema ProxyClassSpecStatefulSetPod#tailscaleContainer
   */
  readonly tailscaleContainer?: ProxyClassSpecStatefulSetPodTailscaleContainer;

  /**
   * Configuration for the proxy init container that enables forwarding.
   *
   * @schema ProxyClassSpecStatefulSetPod#tailscaleInitContainer
   */
  readonly tailscaleInitContainer?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainer;

  /**
   * Proxy Pod's tolerations. By default Tailscale Kubernetes operator does not apply any tolerations. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling
   *
   * @schema ProxyClassSpecStatefulSetPod#tolerations
   */
  readonly tolerations?: ProxyClassSpecStatefulSetPodTolerations[];
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPod' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPod(
  obj: ProxyClassSpecStatefulSetPod | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "annotations": ((obj.annotations) === undefined)
      ? undefined
      : (Object.entries(obj.annotations).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
    "imagePullSecrets": obj.imagePullSecrets?.map((y) =>
      toJson_ProxyClassSpecStatefulSetPodImagePullSecrets(y)
    ),
    "labels": ((obj.labels) === undefined)
      ? undefined
      : (Object.entries(obj.labels).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
    "nodeName": obj.nodeName,
    "nodeSelector": ((obj.nodeSelector) === undefined)
      ? undefined
      : (Object.entries(obj.nodeSelector).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
    "securityContext": toJson_ProxyClassSpecStatefulSetPodSecurityContext(
      obj.securityContext,
    ),
    "tailscaleContainer": toJson_ProxyClassSpecStatefulSetPodTailscaleContainer(
      obj.tailscaleContainer,
    ),
    "tailscaleInitContainer":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainer(
        obj.tailscaleInitContainer,
      ),
    "tolerations": obj.tolerations?.map((y) =>
      toJson_ProxyClassSpecStatefulSetPodTolerations(y)
    ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
 *
 * @schema ProxyClassSpecStatefulSetPodImagePullSecrets
 */
export interface ProxyClassSpecStatefulSetPodImagePullSecrets {
  /**
   * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
   *
   * @schema ProxyClassSpecStatefulSetPodImagePullSecrets#name
   */
  readonly name?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodImagePullSecrets' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodImagePullSecrets(
  obj: ProxyClassSpecStatefulSetPodImagePullSecrets | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Proxy Pod's security context. By default Tailscale Kubernetes operator does not apply any Pod security context. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-2
 *
 * @schema ProxyClassSpecStatefulSetPodSecurityContext
 */
export interface ProxyClassSpecStatefulSetPodSecurityContext {
  /**
   * A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:
   * 1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw----
   * If unset, the Kubelet will not modify the ownership and permissions of any volume. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#fsGroup
   */
  readonly fsGroup?: number;

  /**
   * fsGroupChangePolicy defines behavior of changing ownership and permission of the volume before being exposed inside Pod. This field will only apply to volume types which support fsGroup based ownership(and permissions). It will have no effect on ephemeral volume types such as: secret, configmaps and emptydir. Valid values are "OnRootMismatch" and "Always". If not specified, "Always" is used. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#fsGroupChangePolicy
   */
  readonly fsGroupChangePolicy?: string;

  /**
   * The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#runAsGroup
   */
  readonly runAsGroup?: number;

  /**
   * Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#seLinuxOptions
   */
  readonly seLinuxOptions?:
    ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions;

  /**
   * The seccomp options to use by the containers in this pod. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#seccompProfile
   */
  readonly seccompProfile?:
    ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile;

  /**
   * A list of groups applied to the first process run in each container, in addition to the container's primary GID, the fsGroup (if specified), and group memberships defined in the container image for the uid of the container process. If unspecified, no additional groups are added to any container. Note that group memberships defined in the container image for the uid of the container process are still effective, even if they are not included in this list. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#supplementalGroups
   */
  readonly supplementalGroups?: number[];

  /**
   * Sysctls hold a list of namespaced sysctls used for the pod. Pods with unsupported sysctls (by the container runtime) might fail to launch. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#sysctls
   */
  readonly sysctls?: ProxyClassSpecStatefulSetPodSecurityContextSysctls[];

  /**
   * The Windows specific settings applied to all containers. If unspecified, the options within a container's SecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContext#windowsOptions
   */
  readonly windowsOptions?:
    ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodSecurityContext' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodSecurityContext(
  obj: ProxyClassSpecStatefulSetPodSecurityContext | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "fsGroup": obj.fsGroup,
    "fsGroupChangePolicy": obj.fsGroupChangePolicy,
    "runAsGroup": obj.runAsGroup,
    "runAsNonRoot": obj.runAsNonRoot,
    "runAsUser": obj.runAsUser,
    "seLinuxOptions":
      toJson_ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions(
        obj.seLinuxOptions,
      ),
    "seccompProfile":
      toJson_ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile(
        obj.seccompProfile,
      ),
    "supplementalGroups": obj.supplementalGroups?.map((y) => y),
    "sysctls": obj.sysctls?.map((y) =>
      toJson_ProxyClassSpecStatefulSetPodSecurityContextSysctls(y)
    ),
    "windowsOptions":
      toJson_ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions(
        obj.windowsOptions,
      ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Configuration for the proxy container running tailscale.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainer
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainer {
  /**
   * Container resource requirements. By default Tailscale Kubernetes operator does not apply any resource requirements. The amount of resources required wil depend on the amount of resources the operator needs to parse, usage patterns and cluster size. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainer#resources
   */
  readonly resources?: ProxyClassSpecStatefulSetPodTailscaleContainerResources;

  /**
   * Container security context. Security context specified here will override the security context by the operator. By default the operator: - sets 'privileged: true' for the init container - set NET_ADMIN capability for tailscale container for proxies that are created for Services or Connector. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainer#securityContext
   */
  readonly securityContext?:
    ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainer' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainer(
  obj: ProxyClassSpecStatefulSetPodTailscaleContainer | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "resources": toJson_ProxyClassSpecStatefulSetPodTailscaleContainerResources(
      obj.resources,
    ),
    "securityContext":
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext(
        obj.securityContext,
      ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Configuration for the proxy init container that enables forwarding.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainer
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainer {
  /**
   * Container resource requirements. By default Tailscale Kubernetes operator does not apply any resource requirements. The amount of resources required wil depend on the amount of resources the operator needs to parse, usage patterns and cluster size. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainer#resources
   */
  readonly resources?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerResources;

  /**
   * Container security context. Security context specified here will override the security context by the operator. By default the operator: - sets 'privileged: true' for the init container - set NET_ADMIN capability for tailscale container for proxies that are created for Services or Connector. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainer#securityContext
   */
  readonly securityContext?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainer' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainer(
  obj: ProxyClassSpecStatefulSetPodTailscaleInitContainer | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "resources":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerResources(
        obj.resources,
      ),
    "securityContext":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext(
        obj.securityContext,
      ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The pod this Toleration is attached to tolerates any taint that matches the triple <key,value,effect> using the matching operator <operator>.
 *
 * @schema ProxyClassSpecStatefulSetPodTolerations
 */
export interface ProxyClassSpecStatefulSetPodTolerations {
  /**
   * Effect indicates the taint effect to match. Empty means match all taint effects. When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
   *
   * @schema ProxyClassSpecStatefulSetPodTolerations#effect
   */
  readonly effect?: string;

  /**
   * Key is the taint key that the toleration applies to. Empty means match all taint keys. If the key is empty, operator must be Exists; this combination means to match all values and all keys.
   *
   * @schema ProxyClassSpecStatefulSetPodTolerations#key
   */
  readonly key?: string;

  /**
   * Operator represents a key's relationship to the value. Valid operators are Exists and Equal. Defaults to Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.
   *
   * @default Equal. Exists is equivalent to wildcard for value, so that a pod can tolerate all taints of a particular category.
   * @schema ProxyClassSpecStatefulSetPodTolerations#operator
   */
  readonly operator?: string;

  /**
   * TolerationSeconds represents the period of time the toleration (which must be of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.
   *
   * @schema ProxyClassSpecStatefulSetPodTolerations#tolerationSeconds
   */
  readonly tolerationSeconds?: number;

  /**
   * Value is the taint value the toleration matches to. If the operator is Exists, the value should be empty, otherwise just a regular string.
   *
   * @schema ProxyClassSpecStatefulSetPodTolerations#value
   */
  readonly value?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTolerations' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTolerations(
  obj: ProxyClassSpecStatefulSetPodTolerations | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "effect": obj.effect,
    "key": obj.key,
    "operator": obj.operator,
    "tolerationSeconds": obj.tolerationSeconds,
    "value": obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions
 */
export interface ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions {
  /**
   * Level is SELinux level label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions#level
   */
  readonly level?: string;

  /**
   * Role is a SELinux role label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions#role
   */
  readonly role?: string;

  /**
   * Type is a SELinux type label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions#type
   */
  readonly type?: string;

  /**
   * User is a SELinux user label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions#user
   */
  readonly user?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions(
  obj: ProxyClassSpecStatefulSetPodSecurityContextSeLinuxOptions | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "level": obj.level,
    "role": obj.role,
    "type": obj.type,
    "user": obj.user,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The seccomp options to use by the containers in this pod. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile
 */
export interface ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile {
  /**
   * localhostProfile indicates a profile defined in a file on the node should be used. The profile must be preconfigured on the node to work. Must be a descending path, relative to the kubelet's configured seccomp profile location. Must be set if type is "Localhost". Must NOT be set for any other type.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile#localhostProfile
   */
  readonly localhostProfile?: string;

  /**
   * type indicates which kind of seccomp profile will be applied. Valid options are:
   * Localhost - a profile defined in a file on the node should be used. RuntimeDefault - the container runtime default profile should be used. Unconfined - no profile should be applied.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile#type
   */
  readonly type: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile(
  obj: ProxyClassSpecStatefulSetPodSecurityContextSeccompProfile | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "localhostProfile": obj.localhostProfile,
    "type": obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Sysctl defines a kernel parameter to be set
 *
 * @schema ProxyClassSpecStatefulSetPodSecurityContextSysctls
 */
export interface ProxyClassSpecStatefulSetPodSecurityContextSysctls {
  /**
   * Name of a property to set
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSysctls#name
   */
  readonly name: string;

  /**
   * Value of a property to set
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextSysctls#value
   */
  readonly value: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodSecurityContextSysctls' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodSecurityContextSysctls(
  obj: ProxyClassSpecStatefulSetPodSecurityContextSysctls | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "value": obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The Windows specific settings applied to all containers. If unspecified, the options within a container's SecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
 *
 * @schema ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions
 */
export interface ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions {
  /**
   * GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions#gmsaCredentialSpec
   */
  readonly gmsaCredentialSpec?: string;

  /**
   * GMSACredentialSpecName is the name of the GMSA credential spec to use.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions#gmsaCredentialSpecName
   */
  readonly gmsaCredentialSpecName?: string;

  /**
   * HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
   *
   * @schema ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions#hostProcess
   */
  readonly hostProcess?: boolean;

  /**
   * The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @default the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   * @schema ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions#runAsUserName
   */
  readonly runAsUserName?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions(
  obj: ProxyClassSpecStatefulSetPodSecurityContextWindowsOptions | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "gmsaCredentialSpec": obj.gmsaCredentialSpec,
    "gmsaCredentialSpecName": obj.gmsaCredentialSpecName,
    "hostProcess": obj.hostProcess,
    "runAsUserName": obj.runAsUserName,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Container resource requirements. By default Tailscale Kubernetes operator does not apply any resource requirements. The amount of resources required wil depend on the amount of resources the operator needs to parse, usage patterns and cluster size. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResources
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerResources {
  /**
   * Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container.
   * This is an alpha field and requires enabling the DynamicResourceAllocation feature gate.
   * This field is immutable. It can only be set for containers.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResources#claims
   */
  readonly claims?:
    ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims[];

  /**
   * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResources#limits
   */
  readonly limits?: {
    [key: string]:
      ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits;
  };

  /**
   * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResources#requests
   */
  readonly requests?: {
    [key: string]:
      ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests;
  };
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerResources' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerResources(
  obj: ProxyClassSpecStatefulSetPodTailscaleContainerResources | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "claims": obj.claims?.map((y) =>
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims(y)
    ),
    "limits": ((obj.limits) === undefined)
      ? undefined
      : (Object.entries(obj.limits).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }),
        {},
      )),
    "requests": ((obj.requests) === undefined)
      ? undefined
      : (Object.entries(obj.requests).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }),
        {},
      )),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Container security context. Security context specified here will override the security context by the operator. By default the operator: - sets 'privileged: true' for the init container - set NET_ADMIN capability for tailscale container for proxies that are created for Services or Connector. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext {
  /**
   * AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#capabilities
   */
  readonly capabilities?:
    ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities;

  /**
   * Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default false. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#privileged
   */
  readonly privileged?: boolean;

  /**
   * procMount denotes the type of proc mount to use for the containers. The default is DefaultProcMount which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#procMount
   */
  readonly procMount?: string;

  /**
   * Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default false. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#runAsGroup
   */
  readonly runAsGroup?: number;

  /**
   * Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * The SELinux context to be applied to the container. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#seLinuxOptions
   */
  readonly seLinuxOptions?:
    ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions;

  /**
   * The seccomp options to use by this container. If seccomp options are provided at both the pod & container level, the container options override the pod options. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#seccompProfile
   */
  readonly seccompProfile?:
    ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile;

  /**
   * The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext#windowsOptions
   */
  readonly windowsOptions?:
    ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContext
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "allowPrivilegeEscalation": obj.allowPrivilegeEscalation,
    "capabilities":
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities(
        obj.capabilities,
      ),
    "privileged": obj.privileged,
    "procMount": obj.procMount,
    "readOnlyRootFilesystem": obj.readOnlyRootFilesystem,
    "runAsGroup": obj.runAsGroup,
    "runAsNonRoot": obj.runAsNonRoot,
    "runAsUser": obj.runAsUser,
    "seLinuxOptions":
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions(
        obj.seLinuxOptions,
      ),
    "seccompProfile":
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile(
        obj.seccompProfile,
      ),
    "windowsOptions":
      toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions(
        obj.windowsOptions,
      ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Container resource requirements. By default Tailscale Kubernetes operator does not apply any resource requirements. The amount of resources required wil depend on the amount of resources the operator needs to parse, usage patterns and cluster size. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#resources
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResources
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerResources {
  /**
   * Claims lists the names of resources, defined in spec.resourceClaims, that are used by this container.
   * This is an alpha field and requires enabling the DynamicResourceAllocation feature gate.
   * This field is immutable. It can only be set for containers.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResources#claims
   */
  readonly claims?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims[];

  /**
   * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResources#limits
   */
  readonly limits?: {
    [key: string]:
      ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits;
  };

  /**
   * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. Requests cannot exceed Limits. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResources#requests
   */
  readonly requests?: {
    [key: string]:
      ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests;
  };
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerResources' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerResources(
  obj: ProxyClassSpecStatefulSetPodTailscaleInitContainerResources | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "claims": obj.claims?.map((y) =>
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims(
        y,
      )
    ),
    "limits": ((obj.limits) === undefined)
      ? undefined
      : (Object.entries(obj.limits).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }),
        {},
      )),
    "requests": ((obj.requests) === undefined)
      ? undefined
      : (Object.entries(obj.requests).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1]?.value }),
        {},
      )),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * Container security context. Security context specified here will override the security context by the operator. By default the operator: - sets 'privileged: true' for the init container - set NET_ADMIN capability for tailscale container for proxies that are created for Services or Connector. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext {
  /**
   * AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#capabilities
   */
  readonly capabilities?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities;

  /**
   * Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default false. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#privileged
   */
  readonly privileged?: boolean;

  /**
   * procMount denotes the type of proc mount to use for the containers. The default is DefaultProcMount which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#procMount
   */
  readonly procMount?: string;

  /**
   * Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default false. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#runAsGroup
   */
  readonly runAsGroup?: number;

  /**
   * Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @default user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * The SELinux context to be applied to the container. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#seLinuxOptions
   */
  readonly seLinuxOptions?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions;

  /**
   * The seccomp options to use by this container. If seccomp options are provided at both the pod & container level, the container options override the pod options. Note that this field cannot be set when spec.os.name is windows.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#seccompProfile
   */
  readonly seccompProfile?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile;

  /**
   * The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext#windowsOptions
   */
  readonly windowsOptions?:
    ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContext
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "allowPrivilegeEscalation": obj.allowPrivilegeEscalation,
    "capabilities":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities(
        obj.capabilities,
      ),
    "privileged": obj.privileged,
    "procMount": obj.procMount,
    "readOnlyRootFilesystem": obj.readOnlyRootFilesystem,
    "runAsGroup": obj.runAsGroup,
    "runAsNonRoot": obj.runAsNonRoot,
    "runAsUser": obj.runAsUser,
    "seLinuxOptions":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions(
        obj.seLinuxOptions,
      ),
    "seccompProfile":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile(
        obj.seccompProfile,
      ),
    "windowsOptions":
      toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions(
        obj.windowsOptions,
      ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * ResourceClaim references one entry in PodSpec.ResourceClaims.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims {
  /**
   * Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerResourcesClaims
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits
 */
export class ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits {
  public static fromNumber(
    value: number,
  ): ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits {
    return new ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits(
      value,
    );
  }
  public static fromString(
    value: string,
  ): ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits {
    return new ProxyClassSpecStatefulSetPodTailscaleContainerResourcesLimits(
      value,
    );
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests
 */
export class ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests {
  public static fromNumber(
    value: number,
  ): ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests {
    return new ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests(
      value,
    );
  }
  public static fromString(
    value: string,
  ): ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests {
    return new ProxyClassSpecStatefulSetPodTailscaleContainerResourcesRequests(
      value,
    );
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
 *
 * @default the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities {
  /**
   * Added capabilities
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities#add
   */
  readonly add?: string[];

  /**
   * Removed capabilities
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities#drop
   */
  readonly drop?: string[];
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextCapabilities
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "add": obj.add?.map((y) => y),
    "drop": obj.drop?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The SELinux context to be applied to the container. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions {
  /**
   * Level is SELinux level label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions#level
   */
  readonly level?: string;

  /**
   * Role is a SELinux role label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions#role
   */
  readonly role?: string;

  /**
   * Type is a SELinux type label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions#type
   */
  readonly type?: string;

  /**
   * User is a SELinux user label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions#user
   */
  readonly user?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeLinuxOptions
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "level": obj.level,
    "role": obj.role,
    "type": obj.type,
    "user": obj.user,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The seccomp options to use by this container. If seccomp options are provided at both the pod & container level, the container options override the pod options. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile {
  /**
   * localhostProfile indicates a profile defined in a file on the node should be used. The profile must be preconfigured on the node to work. Must be a descending path, relative to the kubelet's configured seccomp profile location. Must be set if type is "Localhost". Must NOT be set for any other type.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile#localhostProfile
   */
  readonly localhostProfile?: string;

  /**
   * type indicates which kind of seccomp profile will be applied. Valid options are:
   * Localhost - a profile defined in a file on the node should be used. RuntimeDefault - the container runtime default profile should be used. Unconfined - no profile should be applied.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile#type
   */
  readonly type: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextSeccompProfile
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "localhostProfile": obj.localhostProfile,
    "type": obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions
 */
export interface ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions {
  /**
   * GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions#gmsaCredentialSpec
   */
  readonly gmsaCredentialSpec?: string;

  /**
   * GMSACredentialSpecName is the name of the GMSA credential spec to use.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions#gmsaCredentialSpecName
   */
  readonly gmsaCredentialSpecName?: string;

  /**
   * HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions#hostProcess
   */
  readonly hostProcess?: boolean;

  /**
   * The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @default the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   * @schema ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions#runAsUserName
   */
  readonly runAsUserName?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleContainerSecurityContextWindowsOptions
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "gmsaCredentialSpec": obj.gmsaCredentialSpec,
    "gmsaCredentialSpecName": obj.gmsaCredentialSpecName,
    "hostProcess": obj.hostProcess,
    "runAsUserName": obj.runAsUserName,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * ResourceClaim references one entry in PodSpec.ResourceClaims.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims {
  /**
   * Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims#name
   */
  readonly name: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesClaims
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits
 */
export class ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits {
  public static fromNumber(
    value: number,
  ): ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits {
    return new ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits(
      value,
    );
  }
  public static fromString(
    value: string,
  ): ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits {
    return new ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesLimits(
      value,
    );
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests
 */
export class ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests {
  public static fromNumber(
    value: number,
  ): ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests {
    return new ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests(
      value,
    );
  }
  public static fromString(
    value: string,
  ): ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests {
    return new ProxyClassSpecStatefulSetPodTailscaleInitContainerResourcesRequests(
      value,
    );
  }
  private constructor(public readonly value: number | string) {
  }
}

/**
 * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
 *
 * @default the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities {
  /**
   * Added capabilities
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities#add
   */
  readonly add?: string[];

  /**
   * Removed capabilities
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities#drop
   */
  readonly drop?: string[];
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextCapabilities
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "add": obj.add?.map((y) => y),
    "drop": obj.drop?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The SELinux context to be applied to the container. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions {
  /**
   * Level is SELinux level label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions#level
   */
  readonly level?: string;

  /**
   * Role is a SELinux role label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions#role
   */
  readonly role?: string;

  /**
   * Type is a SELinux type label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions#type
   */
  readonly type?: string;

  /**
   * User is a SELinux user label that applies to the container.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions#user
   */
  readonly user?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeLinuxOptions
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "level": obj.level,
    "role": obj.role,
    "type": obj.type,
    "user": obj.user,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The seccomp options to use by this container. If seccomp options are provided at both the pod & container level, the container options override the pod options. Note that this field cannot be set when spec.os.name is windows.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile {
  /**
   * localhostProfile indicates a profile defined in a file on the node should be used. The profile must be preconfigured on the node to work. Must be a descending path, relative to the kubelet's configured seccomp profile location. Must be set if type is "Localhost". Must NOT be set for any other type.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile#localhostProfile
   */
  readonly localhostProfile?: string;

  /**
   * type indicates which kind of seccomp profile will be applied. Valid options are:
   * Localhost - a profile defined in a file on the node should be used. RuntimeDefault - the container runtime default profile should be used. Unconfined - no profile should be applied.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile#type
   */
  readonly type: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextSeccompProfile
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "localhostProfile": obj.localhostProfile,
    "type": obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
 *
 * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions
 */
export interface ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions {
  /**
   * GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions#gmsaCredentialSpec
   */
  readonly gmsaCredentialSpec?: string;

  /**
   * GMSACredentialSpecName is the name of the GMSA credential spec to use.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions#gmsaCredentialSpecName
   */
  readonly gmsaCredentialSpecName?: string;

  /**
   * HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
   *
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions#hostProcess
   */
  readonly hostProcess?: boolean;

  /**
   * The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   *
   * @default the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
   * @schema ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions#runAsUserName
   */
  readonly runAsUserName?: string;
}

/**
 * Converts an object of type 'ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions(
  obj:
    | ProxyClassSpecStatefulSetPodTailscaleInitContainerSecurityContextWindowsOptions
    | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "gmsaCredentialSpec": obj.gmsaCredentialSpec,
    "gmsaCredentialSpecName": obj.gmsaCredentialSpecName,
    "hostProcess": obj.hostProcess,
    "runAsUserName": obj.runAsUserName,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */
