// deno-lint-ignore-file

// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from "npm:cdk8s";
import { Construct } from "npm:constructs";

/**
 * @schema Plan
 */
export class Plan extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Plan"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: "upgrade.cattle.io/v1",
    kind: "Plan",
  };

  /**
   * Renders a Kubernetes manifest for "Plan".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: PlanProps = {}): any {
    return {
      ...Plan.GVK,
      ...toJson_PlanProps(props),
    };
  }

  /**
   * Defines a "Plan" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: PlanProps = {}) {
    super(scope, id, {
      ...Plan.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...Plan.GVK,
      ...toJson_PlanProps(resolved),
    };
  }
}

/**
 * @schema Plan
 */
export interface PlanProps {
  /**
   * @schema Plan#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema Plan#spec
   */
  readonly spec?: PlanSpec;
}

/**
 * Converts an object of type 'PlanProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanProps(
  obj: PlanProps | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "metadata": obj.metadata,
    "spec": toJson_PlanSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpec
 */
export interface PlanSpec {
  /**
   * @schema PlanSpec#channel
   */
  readonly channel?: string;

  /**
   * @schema PlanSpec#concurrency
   */
  readonly concurrency?: number;

  /**
   * @schema PlanSpec#cordon
   */
  readonly cordon?: boolean;

  /**
   * @schema PlanSpec#drain
   */
  readonly drain?: PlanSpecDrain;

  /**
   * @schema PlanSpec#nodeSelector
   */
  readonly nodeSelector?: PlanSpecNodeSelector;

  /**
   * @schema PlanSpec#prepare
   */
  readonly prepare?: PlanSpecPrepare;

  /**
   * @schema PlanSpec#secrets
   */
  readonly secrets?: PlanSpecSecrets[];

  /**
   * @schema PlanSpec#serviceAccountName
   */
  readonly serviceAccountName?: string;

  /**
   * @schema PlanSpec#tolerations
   */
  readonly tolerations?: PlanSpecTolerations[];

  /**
   * @schema PlanSpec#upgrade
   */
  readonly upgrade: PlanSpecUpgrade;

  /**
   * @schema PlanSpec#version
   */
  readonly version?: string;
}

/**
 * Converts an object of type 'PlanSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpec(
  obj: PlanSpec | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "channel": obj.channel,
    "concurrency": obj.concurrency,
    "cordon": obj.cordon,
    "drain": toJson_PlanSpecDrain(obj.drain),
    "nodeSelector": toJson_PlanSpecNodeSelector(obj.nodeSelector),
    "prepare": toJson_PlanSpecPrepare(obj.prepare),
    "secrets": obj.secrets?.map((y) => toJson_PlanSpecSecrets(y)),
    "serviceAccountName": obj.serviceAccountName,
    "tolerations": obj.tolerations?.map((y) => toJson_PlanSpecTolerations(y)),
    "upgrade": toJson_PlanSpecUpgrade(obj.upgrade),
    "version": obj.version,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecDrain
 */
export interface PlanSpecDrain {
  /**
   * @schema PlanSpecDrain#deleteEmptydirData
   */
  readonly deleteEmptydirData?: boolean;

  /**
   * @schema PlanSpecDrain#deleteLocalData
   */
  readonly deleteLocalData?: boolean;

  /**
   * @schema PlanSpecDrain#disableEviction
   */
  readonly disableEviction?: boolean;

  /**
   * @schema PlanSpecDrain#force
   */
  readonly force?: boolean;

  /**
   * @schema PlanSpecDrain#gracePeriod
   */
  readonly gracePeriod?: number;

  /**
   * @schema PlanSpecDrain#ignoreDaemonSets
   */
  readonly ignoreDaemonSets?: boolean;

  /**
   * @schema PlanSpecDrain#podSelector
   */
  readonly podSelector?: PlanSpecDrainPodSelector;

  /**
   * @schema PlanSpecDrain#skipWaitForDeleteTimeout
   */
  readonly skipWaitForDeleteTimeout?: number;

  /**
   * @schema PlanSpecDrain#timeout
   */
  readonly timeout?: number;
}

/**
 * Converts an object of type 'PlanSpecDrain' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecDrain(
  obj: PlanSpecDrain | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "deleteEmptydirData": obj.deleteEmptydirData,
    "deleteLocalData": obj.deleteLocalData,
    "disableEviction": obj.disableEviction,
    "force": obj.force,
    "gracePeriod": obj.gracePeriod,
    "ignoreDaemonSets": obj.ignoreDaemonSets,
    "podSelector": toJson_PlanSpecDrainPodSelector(obj.podSelector),
    "skipWaitForDeleteTimeout": obj.skipWaitForDeleteTimeout,
    "timeout": obj.timeout,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecNodeSelector
 */
export interface PlanSpecNodeSelector {
  /**
   * @schema PlanSpecNodeSelector#matchExpressions
   */
  readonly matchExpressions?: PlanSpecNodeSelectorMatchExpressions[];

  /**
   * @schema PlanSpecNodeSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };
}

/**
 * Converts an object of type 'PlanSpecNodeSelector' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecNodeSelector(
  obj: PlanSpecNodeSelector | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "matchExpressions": obj.matchExpressions?.map((y) =>
      toJson_PlanSpecNodeSelectorMatchExpressions(y)
    ),
    "matchLabels": ((obj.matchLabels) === undefined)
      ? undefined
      : (Object.entries(obj.matchLabels).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepare
 */
export interface PlanSpecPrepare {
  /**
   * @schema PlanSpecPrepare#args
   */
  readonly args?: string[];

  /**
   * @schema PlanSpecPrepare#command
   */
  readonly command?: string[];

  /**
   * @schema PlanSpecPrepare#envFrom
   */
  readonly envFrom?: PlanSpecPrepareEnvFrom[];

  /**
   * @schema PlanSpecPrepare#envs
   */
  readonly envs?: PlanSpecPrepareEnvs[];

  /**
   * @schema PlanSpecPrepare#image
   */
  readonly image?: string;

  /**
   * @schema PlanSpecPrepare#volumes
   */
  readonly volumes?: PlanSpecPrepareVolumes[];
}

/**
 * Converts an object of type 'PlanSpecPrepare' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepare(
  obj: PlanSpecPrepare | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "args": obj.args?.map((y) => y),
    "command": obj.command?.map((y) => y),
    "envFrom": obj.envFrom?.map((y) => toJson_PlanSpecPrepareEnvFrom(y)),
    "envs": obj.envs?.map((y) => toJson_PlanSpecPrepareEnvs(y)),
    "image": obj.image,
    "volumes": obj.volumes?.map((y) => toJson_PlanSpecPrepareVolumes(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecSecrets
 */
export interface PlanSpecSecrets {
  /**
   * @schema PlanSpecSecrets#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecSecrets#path
   */
  readonly path?: string;
}

/**
 * Converts an object of type 'PlanSpecSecrets' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecSecrets(
  obj: PlanSpecSecrets | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "path": obj.path,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecTolerations
 */
export interface PlanSpecTolerations {
  /**
   * @schema PlanSpecTolerations#effect
   */
  readonly effect?: string;

  /**
   * @schema PlanSpecTolerations#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecTolerations#operator
   */
  readonly operator?: string;

  /**
   * @schema PlanSpecTolerations#tolerationSeconds
   */
  readonly tolerationSeconds?: number;

  /**
   * @schema PlanSpecTolerations#value
   */
  readonly value?: string;
}

/**
 * Converts an object of type 'PlanSpecTolerations' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecTolerations(
  obj: PlanSpecTolerations | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "effect": obj.effect,
    "key": obj.key,
    "operator": obj.operator,
    "tolerationSeconds": obj.tolerationSeconds,
    "value": obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgrade
 */
export interface PlanSpecUpgrade {
  /**
   * @schema PlanSpecUpgrade#args
   */
  readonly args?: string[];

  /**
   * @schema PlanSpecUpgrade#command
   */
  readonly command?: string[];

  /**
   * @schema PlanSpecUpgrade#envFrom
   */
  readonly envFrom?: PlanSpecUpgradeEnvFrom[];

  /**
   * @schema PlanSpecUpgrade#envs
   */
  readonly envs?: PlanSpecUpgradeEnvs[];

  /**
   * @schema PlanSpecUpgrade#image
   */
  readonly image?: string;

  /**
   * @schema PlanSpecUpgrade#volumes
   */
  readonly volumes?: PlanSpecUpgradeVolumes[];
}

/**
 * Converts an object of type 'PlanSpecUpgrade' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgrade(
  obj: PlanSpecUpgrade | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "args": obj.args?.map((y) => y),
    "command": obj.command?.map((y) => y),
    "envFrom": obj.envFrom?.map((y) => toJson_PlanSpecUpgradeEnvFrom(y)),
    "envs": obj.envs?.map((y) => toJson_PlanSpecUpgradeEnvs(y)),
    "image": obj.image,
    "volumes": obj.volumes?.map((y) => toJson_PlanSpecUpgradeVolumes(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecDrainPodSelector
 */
export interface PlanSpecDrainPodSelector {
  /**
   * @schema PlanSpecDrainPodSelector#matchExpressions
   */
  readonly matchExpressions?: PlanSpecDrainPodSelectorMatchExpressions[];

  /**
   * @schema PlanSpecDrainPodSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };
}

/**
 * Converts an object of type 'PlanSpecDrainPodSelector' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecDrainPodSelector(
  obj: PlanSpecDrainPodSelector | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "matchExpressions": obj.matchExpressions?.map((y) =>
      toJson_PlanSpecDrainPodSelectorMatchExpressions(y)
    ),
    "matchLabels": ((obj.matchLabels) === undefined)
      ? undefined
      : (Object.entries(obj.matchLabels).reduce(
        (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
        {},
      )),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecNodeSelectorMatchExpressions
 */
export interface PlanSpecNodeSelectorMatchExpressions {
  /**
   * @schema PlanSpecNodeSelectorMatchExpressions#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecNodeSelectorMatchExpressions#operator
   */
  readonly operator?: string;

  /**
   * @schema PlanSpecNodeSelectorMatchExpressions#values
   */
  readonly values?: string[];
}

/**
 * Converts an object of type 'PlanSpecNodeSelectorMatchExpressions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecNodeSelectorMatchExpressions(
  obj: PlanSpecNodeSelectorMatchExpressions | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "operator": obj.operator,
    "values": obj.values?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvFrom
 */
export interface PlanSpecPrepareEnvFrom {
  /**
   * @schema PlanSpecPrepareEnvFrom#configMapRef
   */
  readonly configMapRef?: PlanSpecPrepareEnvFromConfigMapRef;

  /**
   * @schema PlanSpecPrepareEnvFrom#prefix
   */
  readonly prefix?: string;

  /**
   * @schema PlanSpecPrepareEnvFrom#secretRef
   */
  readonly secretRef?: PlanSpecPrepareEnvFromSecretRef;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvFrom(
  obj: PlanSpecPrepareEnvFrom | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "configMapRef": toJson_PlanSpecPrepareEnvFromConfigMapRef(obj.configMapRef),
    "prefix": obj.prefix,
    "secretRef": toJson_PlanSpecPrepareEnvFromSecretRef(obj.secretRef),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvs
 */
export interface PlanSpecPrepareEnvs {
  /**
   * @schema PlanSpecPrepareEnvs#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareEnvs#value
   */
  readonly value?: string;

  /**
   * @schema PlanSpecPrepareEnvs#valueFrom
   */
  readonly valueFrom?: PlanSpecPrepareEnvsValueFrom;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvs' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvs(
  obj: PlanSpecPrepareEnvs | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "value": obj.value,
    "valueFrom": toJson_PlanSpecPrepareEnvsValueFrom(obj.valueFrom),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareVolumes
 */
export interface PlanSpecPrepareVolumes {
  /**
   * @schema PlanSpecPrepareVolumes#destination
   */
  readonly destination?: string;

  /**
   * @schema PlanSpecPrepareVolumes#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareVolumes#source
   */
  readonly source?: string;
}

/**
 * Converts an object of type 'PlanSpecPrepareVolumes' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareVolumes(
  obj: PlanSpecPrepareVolumes | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "destination": obj.destination,
    "name": obj.name,
    "source": obj.source,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvFrom
 */
export interface PlanSpecUpgradeEnvFrom {
  /**
   * @schema PlanSpecUpgradeEnvFrom#configMapRef
   */
  readonly configMapRef?: PlanSpecUpgradeEnvFromConfigMapRef;

  /**
   * @schema PlanSpecUpgradeEnvFrom#prefix
   */
  readonly prefix?: string;

  /**
   * @schema PlanSpecUpgradeEnvFrom#secretRef
   */
  readonly secretRef?: PlanSpecUpgradeEnvFromSecretRef;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvFrom(
  obj: PlanSpecUpgradeEnvFrom | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "configMapRef": toJson_PlanSpecUpgradeEnvFromConfigMapRef(obj.configMapRef),
    "prefix": obj.prefix,
    "secretRef": toJson_PlanSpecUpgradeEnvFromSecretRef(obj.secretRef),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvs
 */
export interface PlanSpecUpgradeEnvs {
  /**
   * @schema PlanSpecUpgradeEnvs#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeEnvs#value
   */
  readonly value?: string;

  /**
   * @schema PlanSpecUpgradeEnvs#valueFrom
   */
  readonly valueFrom?: PlanSpecUpgradeEnvsValueFrom;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvs' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvs(
  obj: PlanSpecUpgradeEnvs | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "value": obj.value,
    "valueFrom": toJson_PlanSpecUpgradeEnvsValueFrom(obj.valueFrom),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeVolumes
 */
export interface PlanSpecUpgradeVolumes {
  /**
   * @schema PlanSpecUpgradeVolumes#destination
   */
  readonly destination?: string;

  /**
   * @schema PlanSpecUpgradeVolumes#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeVolumes#source
   */
  readonly source?: string;
}

/**
 * Converts an object of type 'PlanSpecUpgradeVolumes' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeVolumes(
  obj: PlanSpecUpgradeVolumes | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "destination": obj.destination,
    "name": obj.name,
    "source": obj.source,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecDrainPodSelectorMatchExpressions
 */
export interface PlanSpecDrainPodSelectorMatchExpressions {
  /**
   * @schema PlanSpecDrainPodSelectorMatchExpressions#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecDrainPodSelectorMatchExpressions#operator
   */
  readonly operator?: string;

  /**
   * @schema PlanSpecDrainPodSelectorMatchExpressions#values
   */
  readonly values?: string[];
}

/**
 * Converts an object of type 'PlanSpecDrainPodSelectorMatchExpressions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecDrainPodSelectorMatchExpressions(
  obj: PlanSpecDrainPodSelectorMatchExpressions | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "operator": obj.operator,
    "values": obj.values?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvFromConfigMapRef
 */
export interface PlanSpecPrepareEnvFromConfigMapRef {
  /**
   * @schema PlanSpecPrepareEnvFromConfigMapRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareEnvFromConfigMapRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvFromConfigMapRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvFromConfigMapRef(
  obj: PlanSpecPrepareEnvFromConfigMapRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvFromSecretRef
 */
export interface PlanSpecPrepareEnvFromSecretRef {
  /**
   * @schema PlanSpecPrepareEnvFromSecretRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareEnvFromSecretRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvFromSecretRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvFromSecretRef(
  obj: PlanSpecPrepareEnvFromSecretRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvsValueFrom
 */
export interface PlanSpecPrepareEnvsValueFrom {
  /**
   * @schema PlanSpecPrepareEnvsValueFrom#configMapKeyRef
   */
  readonly configMapKeyRef?: PlanSpecPrepareEnvsValueFromConfigMapKeyRef;

  /**
   * @schema PlanSpecPrepareEnvsValueFrom#fieldRef
   */
  readonly fieldRef?: PlanSpecPrepareEnvsValueFromFieldRef;

  /**
   * @schema PlanSpecPrepareEnvsValueFrom#resourceFieldRef
   */
  readonly resourceFieldRef?: PlanSpecPrepareEnvsValueFromResourceFieldRef;

  /**
   * @schema PlanSpecPrepareEnvsValueFrom#secretKeyRef
   */
  readonly secretKeyRef?: PlanSpecPrepareEnvsValueFromSecretKeyRef;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvsValueFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvsValueFrom(
  obj: PlanSpecPrepareEnvsValueFrom | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "configMapKeyRef": toJson_PlanSpecPrepareEnvsValueFromConfigMapKeyRef(
      obj.configMapKeyRef,
    ),
    "fieldRef": toJson_PlanSpecPrepareEnvsValueFromFieldRef(obj.fieldRef),
    "resourceFieldRef": toJson_PlanSpecPrepareEnvsValueFromResourceFieldRef(
      obj.resourceFieldRef,
    ),
    "secretKeyRef": toJson_PlanSpecPrepareEnvsValueFromSecretKeyRef(
      obj.secretKeyRef,
    ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvFromConfigMapRef
 */
export interface PlanSpecUpgradeEnvFromConfigMapRef {
  /**
   * @schema PlanSpecUpgradeEnvFromConfigMapRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeEnvFromConfigMapRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvFromConfigMapRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvFromConfigMapRef(
  obj: PlanSpecUpgradeEnvFromConfigMapRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvFromSecretRef
 */
export interface PlanSpecUpgradeEnvFromSecretRef {
  /**
   * @schema PlanSpecUpgradeEnvFromSecretRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeEnvFromSecretRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvFromSecretRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvFromSecretRef(
  obj: PlanSpecUpgradeEnvFromSecretRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvsValueFrom
 */
export interface PlanSpecUpgradeEnvsValueFrom {
  /**
   * @schema PlanSpecUpgradeEnvsValueFrom#configMapKeyRef
   */
  readonly configMapKeyRef?: PlanSpecUpgradeEnvsValueFromConfigMapKeyRef;

  /**
   * @schema PlanSpecUpgradeEnvsValueFrom#fieldRef
   */
  readonly fieldRef?: PlanSpecUpgradeEnvsValueFromFieldRef;

  /**
   * @schema PlanSpecUpgradeEnvsValueFrom#resourceFieldRef
   */
  readonly resourceFieldRef?: PlanSpecUpgradeEnvsValueFromResourceFieldRef;

  /**
   * @schema PlanSpecUpgradeEnvsValueFrom#secretKeyRef
   */
  readonly secretKeyRef?: PlanSpecUpgradeEnvsValueFromSecretKeyRef;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvsValueFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvsValueFrom(
  obj: PlanSpecUpgradeEnvsValueFrom | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "configMapKeyRef": toJson_PlanSpecUpgradeEnvsValueFromConfigMapKeyRef(
      obj.configMapKeyRef,
    ),
    "fieldRef": toJson_PlanSpecUpgradeEnvsValueFromFieldRef(obj.fieldRef),
    "resourceFieldRef": toJson_PlanSpecUpgradeEnvsValueFromResourceFieldRef(
      obj.resourceFieldRef,
    ),
    "secretKeyRef": toJson_PlanSpecUpgradeEnvsValueFromSecretKeyRef(
      obj.secretKeyRef,
    ),
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvsValueFromConfigMapKeyRef
 */
export interface PlanSpecPrepareEnvsValueFromConfigMapKeyRef {
  /**
   * @schema PlanSpecPrepareEnvsValueFromConfigMapKeyRef#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromConfigMapKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromConfigMapKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvsValueFromConfigMapKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvsValueFromConfigMapKeyRef(
  obj: PlanSpecPrepareEnvsValueFromConfigMapKeyRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvsValueFromFieldRef
 */
export interface PlanSpecPrepareEnvsValueFromFieldRef {
  /**
   * @schema PlanSpecPrepareEnvsValueFromFieldRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromFieldRef#fieldPath
   */
  readonly fieldPath?: string;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvsValueFromFieldRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvsValueFromFieldRef(
  obj: PlanSpecPrepareEnvsValueFromFieldRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "apiVersion": obj.apiVersion,
    "fieldPath": obj.fieldPath,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvsValueFromResourceFieldRef
 */
export interface PlanSpecPrepareEnvsValueFromResourceFieldRef {
  /**
   * @schema PlanSpecPrepareEnvsValueFromResourceFieldRef#containerName
   */
  readonly containerName?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromResourceFieldRef#divisor
   */
  readonly divisor?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromResourceFieldRef#resource
   */
  readonly resource?: string;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvsValueFromResourceFieldRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvsValueFromResourceFieldRef(
  obj: PlanSpecPrepareEnvsValueFromResourceFieldRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "containerName": obj.containerName,
    "divisor": obj.divisor,
    "resource": obj.resource,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecPrepareEnvsValueFromSecretKeyRef
 */
export interface PlanSpecPrepareEnvsValueFromSecretKeyRef {
  /**
   * @schema PlanSpecPrepareEnvsValueFromSecretKeyRef#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromSecretKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecPrepareEnvsValueFromSecretKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecPrepareEnvsValueFromSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecPrepareEnvsValueFromSecretKeyRef(
  obj: PlanSpecPrepareEnvsValueFromSecretKeyRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvsValueFromConfigMapKeyRef
 */
export interface PlanSpecUpgradeEnvsValueFromConfigMapKeyRef {
  /**
   * @schema PlanSpecUpgradeEnvsValueFromConfigMapKeyRef#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromConfigMapKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromConfigMapKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvsValueFromConfigMapKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvsValueFromConfigMapKeyRef(
  obj: PlanSpecUpgradeEnvsValueFromConfigMapKeyRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvsValueFromFieldRef
 */
export interface PlanSpecUpgradeEnvsValueFromFieldRef {
  /**
   * @schema PlanSpecUpgradeEnvsValueFromFieldRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromFieldRef#fieldPath
   */
  readonly fieldPath?: string;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvsValueFromFieldRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvsValueFromFieldRef(
  obj: PlanSpecUpgradeEnvsValueFromFieldRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "apiVersion": obj.apiVersion,
    "fieldPath": obj.fieldPath,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvsValueFromResourceFieldRef
 */
export interface PlanSpecUpgradeEnvsValueFromResourceFieldRef {
  /**
   * @schema PlanSpecUpgradeEnvsValueFromResourceFieldRef#containerName
   */
  readonly containerName?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromResourceFieldRef#divisor
   */
  readonly divisor?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromResourceFieldRef#resource
   */
  readonly resource?: string;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvsValueFromResourceFieldRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvsValueFromResourceFieldRef(
  obj: PlanSpecUpgradeEnvsValueFromResourceFieldRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "containerName": obj.containerName,
    "divisor": obj.divisor,
    "resource": obj.resource,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */

/**
 * @schema PlanSpecUpgradeEnvsValueFromSecretKeyRef
 */
export interface PlanSpecUpgradeEnvsValueFromSecretKeyRef {
  /**
   * @schema PlanSpecUpgradeEnvsValueFromSecretKeyRef#key
   */
  readonly key?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromSecretKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema PlanSpecUpgradeEnvsValueFromSecretKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'PlanSpecUpgradeEnvsValueFromSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_PlanSpecUpgradeEnvsValueFromSecretKeyRef(
  obj: PlanSpecUpgradeEnvsValueFromSecretKeyRef | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) return undefined;
  const result = {
    "key": obj.key,
    "name": obj.name,
    "optional": obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }),
    {},
  );
}
/* eslint-enable max-len, quote-props */
