# TODO: add markdownlint
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.17.1
    hooks:
      - id: renovate-config-validator
  - repo: local
    hooks:
      - id: check
        name: run check
        entry: bash -c 'cd src/cdk8s/ && true'
        language: system
        types: [ts]
        pass_filenames: false
  - repo: local
    hooks:
      - id: run
        name: build k8s manifest
        entry: bash -c '(cd src/cdk8s/ && bun install && bun run src/app.ts)'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: run
        name: kube-linter
        entry: bash -c 'kube-linter lint src/cdk8s/dist/'
        language: system
        pass_filenames: false
  # note: you need to run `pre-commit install --hook-type commit-msg`
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        language_version: "22.8.0"
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
