# TODO: add markdownlint
repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 40.36.8
    hooks:
      - id: renovate-config-validator
  - repo: local
    hooks:
      - id: check
        name: run deno check
        entry: bash -c 'cd cdk8s/ && deno check src/app.ts'
        language: system
        types: [ts]
        pass_filenames: false
  - repo: local
    hooks:
      - id: run
        name: build k8s manifest
        entry: bash -c 'cd cdk8s/ && deno task build'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: run
        name: kube-linter
        entry: bash -c 'kube-linter lint cdk8s/dist/'
        language: system
        pass_filenames: false
  # note: you need to run `pre-commit install --hook-type commit-msg`
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        language_version: "22.8.0"
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
