[tools]
bun = "latest"
node = "lts"
python = "latest"

[tasks.check]
description = "Check"
run = "dagger call check-all --source=."

[tasks.ci]
run = 'dagger call ci --argocd-token=env:DUMMY_ARGOCD_TOKEN --chart-museum-password=env:DUMMY_CHART_MUSEUM_PASSWORD --chart-museum-username=dummy-user --chart-version=0.1.0-dev --ghcr-password=env:DUMMY_GHCR_PASSWORD --ghcr-username=dummy-user --env=dev --hass-base-url=env:HASS_BASE_URL --hass-token=env:HASS_TOKEN'

[tasks.dev]
run = 'bun install && dagger develop && (cd .dagger/ && bun install) && (cd src/ha/ && ./generate-types.ts)'

[tasks.build-cdk8s]
dir = 'src/cdk8s/'
run = ['bun run typecheck', 'bun run lint', 'bun run build']

[tasks.build-ha]
dir = 'src/ha/'
run = ['bun run typecheck', 'bun run lint']

[tasks.build-helm-types]
dir = 'src/helm-types/'
run = ['bun run typecheck', 'bun run lint']

[tasks.build-dagger]
dir = '.dagger/'
run = ['bun run typecheck', 'bun run lint']

[tasks.build]
depends = ['build-cdk8s', 'build-ha', 'build-helm-types', 'build-dagger']
