- id: "1717034922936"
  alias: Early Morning
  description: Set the AC one hour before waking up
  trigger:
    - alias: One hour before waking up
      platform: template
      value_template:
        '{{ now().strftime("%H:%M:%S") == (today_at(states("input_datetime.wake_up"))-timedelta(hours=1)).strftime("%H:%M:%S")
        }} '
  condition: []
  action:
    - alias: Set thermostat
      action: climate.set_temperature
      target:
        entity_id: climate.living_room_ac
      data:
        hvac_mode: heat
        temperature: 22
    - alias: Set fan mode
      action: climate.set_fan_mode
      target:
        entity_id: climate.living_room_ac
      data:
        fan_mode: auto
    - alias: Set swing mode
      action: climate.set_swing_mode
      target:
        entity_id: climate.living_room_ac
      data:
        swing_mode: auto
    - alias: Set bedroom heater
      action: climate.set_temperature
      target:
        entity_id: climate.bedroom_thermostat
      data:
        hvac_mode: heat
        temperature: 24
  mode: single
