- id: "1647291929910"
  alias: Leaving Home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.home
      event: leave
      alias: Jerred leaves home
  condition: []
  action:
    - alias: Lower thermostat
      action: climate.turn_off
      target:
        entity_id: climate.living_room_ac
    - alias: Turn on the Roomba
      if:
        - condition: time
          before: "19:00:00"
          after: 07:00:00
          alias: Within Roomba operating hours
      then:
        - data: {}
          target:
            entity_id: vacuum.roomba
          action: vacuum.start
          alias: Start Roomba
  mode: single
