- id: "1647291874140"
  alias: Welcome Home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.home
      event: enter
      alias: Jerred enters home zone
  condition: []
  action:
    - alias: Turn off AC
      action: climate.set_temperature
      target:
        entity_id: climate.living_room_ac
      data:
        hvac_mode: heat
        temperature: 22
    - alias: Send Roomba home
      if:
        - condition: and
          conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba
                  attribute: status
                  state: Charging
                  alias: Roomba is not charging
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba
                  attribute: status
                  state: Docked
                  alias: Roomba is not docked
          alias: Roomba is not docked or charging
          enabled: true
      then:
        - data: {}
          target:
            entity_id: vacuum.roomba
          alias: Send the Roomba home
          action: vacuum.return_to_base
  mode: single
