- id: "1647291874140"
  alias: Welcome Home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.home
      event: enter
      alias: Jerred enters home zone
  condition: []
  action:
    - alias: Turn on lights
      action: scene.turn_on
      target:
        entity_id: scene.dining_room_bright
      data: {}
    - alias: Send Roomba home
      if:
        - condition: and
          conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba_combo
                  attribute: status
                  state: Charging
                  alias: Roomba is not charging
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba_combo
                  attribute: status
                  state: Docked
                  alias: Roomba is not docked
          alias: Roomba is not docked or charging
          enabled: true
      then:
        - data: {}
          target:
            entity_id: vacuum.roomba_combo
          alias: Send the Roomba home
          action: vacuum.return_to_base
  mode: single
