VERSION 0.6
FROM alpine
WORKDIR /workspace

rsync:
  RUN apk add rsync openssh
  RUN mkdir -p /root/.ssh/
  COPY ssh/known_hosts /root/.ssh/known_hosts

deploy:
  FROM +rsync
  COPY +render/ .
  RUN --no-cache --ssh rsync --progress -a --checksum . jerred@public.zeus.sjer.red:/home/jerred/config

up:
  FROM +deploy
  RUN --no-cache --ssh ssh jerred@public.zeus.sjer.red "cd /home/jerred/config && docker-compose up -d"

render:
  COPY config ./config/
  COPY static ./static/
  COPY ../common+caddy/ ./config/caddy
  COPY ../common+config.vars/ .
  COPY ../common+config.blackbox/ ./config
  COPY +render.varken/ ./config/
  COPY +render.wireguard/ ./config/wireguard/
  COPY +render.docker-compose/ ./
  SAVE ARTIFACT *

lint:
  FROM ../common+lint.docker-compose
  COPY docker-compose.yml .
  RUN ./lint.py

gomplate:
  FROM golang:alpine
  WORKDIR /workspace
  RUN go install github.com/hairyhenderson/gomplate/v3/cmd/gomplate@latest

render.docker-compose:
  FROM +gomplate
  COPY docker-compose.yml .
  RUN --secret=DATADOG_API_KEY=+secrets/sj/datadog_api_key --secret=AWS_ACCESS_KEY_ID=+secrets/sj/aws_access_key_id --secret=AWS_SECRET_ACCESS_KEY=+secrets/sj/aws_secret_access_key gomplate -f docker-compose.yml -o docker-compose.yml
  SAVE ARTIFACT docker-compose.yml

render.wireguard:
  FROM +gomplate
  COPY config/wireguard/wg0.conf .
  RUN --secret=WIREGUARD_PRIVATE_KEY=+secrets/sj/wireguard/privatekey --secret=WIREGUARD_PUBLIC_KEY=+secrets/sj/wireguard/publickey --secret=WIREGUARD_PRESHARED_KEY=+secrets/sj/wireguard/presharedkey gomplate -f wg0.conf -o wg0.conf
  SAVE ARTIFACT wg0.conf

render.varken:
  FROM +gomplate
  COPY config/varken.ini .
  RUN --secret=MAXMIND_LICENSE_KEY=+secrets/sj/zeus/maxmind_license_key --secret=INFLUXDB_PASSWORD=+secrets/sj/zeus/influxdb_password --secret=TAUTULLI_API_KEY=+secrets/sj/zeus/tautulli_api_key --secret=SONARR_API_KEY=+secrets/sj/zeus/sonarr_api_key --secret=RADARR_API_KEY=+secrets/sj/zeus/radarr_api_key gomplate -f varken.ini -o varken.ini
  SAVE ARTIFACT varken.ini
