VERSION 0.8
PROJECT sjerred/homelab

deno:
  FROM denoland/deno
  WORKDIR /workspace

# download and cache dependencies
deps:
  FROM +deno
  CACHE --persist $DENO_DIR
  COPY --dir deno* src imports patch.ts .
  RUN deno install --frozen=true --reload

build:
  FROM +deps
  COPY --dir config .
  RUN deno task build
  SAVE ARTIFACT dist AS LOCAL dist

# update Deno lockfile
lock:
  FROM +deno
  COPY --dir deno.json .
  RUN deno install
  SAVE ARTIFACT deno.lock AS LOCAL deno.lock
