default_config:

homekit:
  - name: HA1
    advertise_ip: 192.168.1.81
    port: 21063
    filter:
      include_domains:
        - climate
        - cover
        - fan
        - humidifier
        - alarm_control_panel
        - remote
        - water_heater
        - sensor
        - switch
        - device_tracker
        - binary_sensor
        - input_select
        - vacuum
        - script
      exclude_entities:
        - binary_sensor.iphone_focus
        - binary_sensor.ipad_focus
        - binary_sensor.roomba_bin_full
        - script.close_covers_with_delay
        - script.open_covers_with_delay
      exclude_entity_globs:
        - binary_sensor.*entertainment_configuration
        - switch.adaptive_lighting_*
        - sensor.the_victor_229_*
        - sensor.average_*
        - sensor.current_bill*
        - sensor.typical_monthly*
        - sensor.electricity_maps*
  - name: HA2
    advertise_ip: 192.168.1.81
    port: 21064
    filter:
      include_domains:
        - light

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
sonos:
  media_player:
    advertise_addr: 192.168.1.81

recorder:
  commit_interval: 10
  purge_keep_days: 90

# Text to speech
tts:
  - platform: google_translate
ffmpeg:

automation: !include_dir_merge_list automation
scene: !include scenes.yaml
script: !include scripts.yaml

light:
  - platform: group
    name: "Bronze Lamp"
    unique_id: bronze_lamp
    entities:
      - light.bronze_lamp_upper
      - light.bronze_lamp_lower
      - light.bronze_lamp_middle

input_boolean:
  sun_is_down:
    name: Sun is down
    icon: mdi:weather-sunset-down
  holiday_lights_enabled:
    name: Holiday Lights Enabled
    icon: phu:light-string
  awake:
    name: Awake
    icon: mdi:sleep

input_datetime:
  wake_up:
    name: "Wake up"
    has_date: false
    icon: "mdi:weather-sunny"
    has_time: true
