open_covers_with_delay:
  alias: Open Covers with Delay
  description: "Open covers with a delay between each"
  fields:
    cover_entities:
      description: "List of cover entities to open"
      example: "cover.living_room, cover.bedroom"
  sequence:
    - repeat:
        count: "{{ cover_entities | length }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: "{{ cover_entities[repeat.index - 1] }}"
          - delay: "00:00:01"
  mode: single
  max_exceeded: silent
