open_covers_with_delay:
  alias: Open Covers with Delay
  description: "Open covers with a delay between each"
  fields:
    cover_entities:
      description: "List of cover entities to open"
      example: "cover.living_room, cover.bedroom"
  sequence:
    - repeat:
        count: "{{ cover_entities.split(',') | length }}"
        sequence:
          - action: cover.open_cover
            target:
              entity_id: "{{ cover_entities.split(',')[repeat.index - 1] }}"
          - delay: "00:00:01"
  mode: single
  max_exceeded: silent
close_covers_with_delay:
  alias: Close Covers with Delay
  description: "Close covers with a delay between each"
  fields:
    cover_entities:
      description: "List of cover entities to close"
      example: "cover.living_room, cover.bedroom"
  sequence:
    - repeat:
        count: "{{ cover_entities.split(',') | length }}"
        sequence:
          - action: cover.close_cover
            target:
              entity_id: "{{ cover_entities.split(',')[repeat.index - 1] }}"
          - delay: "00:00:01"
  mode: single
  max_exceeded: silent

open_living_room_covers:
  alias: Open Living Room Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.living_room_left, cover.living_room_right"

close_living_room_covers:
  alias: Close Living Room Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.living_room_left, cover.living_room_right"

open_all_living_room_tv_covers:
  alias: Open All Living Room and TV Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.living_room_left, cover.living_room_right, cover.tv_left, cover.tv_right"

close_all_living_room_tv_covers:
  alias: Close All Living Room and TV Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.living_room_left, cover.living_room_right, cover.tv_left, cover.tv_right"

open_tv_covers:
  alias: Open TV Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.tv_left, cover.tv_right"

close_tv_covers:
  alias: Close TV Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.tv_left, cover.tv_right"

open_kitchen_covers:
  alias: Open Kitchen Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.kitchen_left, cover.kitchen_right"

close_kitchen_covers:
  alias: Close Kitchen Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.kitchen_left, cover.kitchen_right"

open_bedroom_covers:
  alias: Open Bedroom Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.bedroom_left, cover.bedroom_right"

close_bedroom_covers:
  alias: Close Bedroom Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.bedroom_left, cover.bedroom_right"

open_office_covers:
  alias: Open Office Covers
  sequence:
    action: script.open_covers_with_delay
    data:
      cover_entities: "cover.office_left, cover.office_right"

close_office_covers:
  alias: Close Office Covers
  sequence:
    action: script.close_covers_with_delay
    data:
      cover_entities: "cover.office_left, cover.office_right"
