VERSION 0.7
FROM alpine
WORKDIR /workspace

lint.docker-compose:
  FROM python:slim
  WORKDIR /workspace
  RUN pip install --upgrade pip
  COPY requirements.txt .
  RUN pip install -r requirements.txt
  COPY lint.py .
