apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://helm.datadoghq.com"
    targetRevision: 1.2.2
    chart: datadog-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: datadog
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
