VERSION 0.8
PROJECT sjerred/homelab

FROM alpine/helm:3
WORKDIR /workspace

build:
  ARG --required version
  COPY . .
  COPY ../+build/* templates/

  RUN sed -i "s/^version:.*$/version: $version/" Chart.yaml
  RUN sed -i "s/^appVersion:.*$/appVersion: $version/" Chart.yaml

  # fixes an issue with Home Assistant YAML files
  # escape {{ and }} in all of the files
  # https://github.com/helm/helm/issues/2798#issuecomment-326454957
  # {{ => {{`
  # }} => `}}
  RUN find . -type f -name '*.yaml' -exec sed -i 's/{{/{{`{{/g' {} +
  RUN find . -type f -name '*.yaml' -exec sed -i 's/}}/}}`}}/g' {} +

  # print line 1371
  RUN sed -n 1371p templates/lamport.k8s.yaml
  RUN false

  RUN helm package .
  SAVE ARTIFACT lamport-$version.tgz AS LOCAL dist/

publish:
  ARG repo=https://chartmuseum.tailnet-1a49.ts.net
  ARG --required version
  COPY +build/ .
  RUN --secret=chartmuseum_username --secret=chartmuseum_password --push --no-cache curl -f -u $chartmuseum_username:$chartmuseum_password --data-binary "@lamport-$version.tgz" $repo/api/charts
