VERSION 0.6
FROM alpine

deps:
  FROM node:lts
  WORKDIR /workspace
  RUN npm install --location=global npm@latest
  COPY package*.json .
  RUN npm install

build:
  FROM +deps
  COPY . .
  RUN npm run build

deploy:
  FROM +build
  RUN --secret AWS_ACCESS_KEY_ID=+secrets/user/servers/zeus/aws_access_key_id --secret AWS_SECRET_ACCESS_KEY=+secrets/user/servers/zeus/aws_secret_access_key npm run cdk -- deploy --all

lint:
  FROM +deps
  COPY . .
  RUN npm run lint

lint.fix:
  FROM +deps
  COPY . .
  RUN npm run lint:fix
  SAVE ARTIFACT * AS LOCAL ./
