VERSION 0.8
PROJECT sjerred/homelab

deno:
  FROM denoland/deno
  WORKDIR /workspace

build:
  FROM +deno
  COPY --dir deno* src imports config vendor patch.ts .
  RUN deno task build
  SAVE ARTIFACT dist AS LOCAL dist
